import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/quickstart',
        'getting-started/install',
        'getting-started/pipe-mode',
        'getting-started/server-mode',
        'getting-started/first-query',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'category',
          label: 'Ingest Data',
          link: {type: 'doc', id: 'guides/ingest-data'},
          items: [
            'guides/ingest-data/filebeat',
            'guides/ingest-data/fluent-bit',
            'guides/ingest-data/vector',
            'guides/ingest-data/opentelemetry',
            'guides/ingest-data/splunk-hec',
          ],
        },
        'guides/search-and-filter',
        'guides/aggregations',
        'guides/field-extraction',
        'guides/json-processing',
        'guides/kubernetes-audit-logs',
        'guides/time-series',
        'guides/materialized-views',
        'guides/saved-queries',
        'guides/live-tail',
        'guides/ctes-and-joins',
        'guides/scripting-and-pipes',
      ],
    },
    {
      type: 'category',
      label: 'LynxFlow v2 Reference',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'LynxFlow v2 Reference',
        description:
          'The LynxFlow v2 query language: operators, scalar functions, and aggregate functions. Generated from the registry (pkg/lynxflow/registry) by internal/docgen.',
        slug: '/lynxflow/overview',
      },
      items: [
        {
          type: 'category',
          label: 'Operators',
          items: [
            'lynxflow/operators/from',
            'lynxflow/operators/where',
            'lynxflow/operators/parse',
            'lynxflow/operators/extend',
            'lynxflow/operators/keep',
            'lynxflow/operators/drop',
            'lynxflow/operators/rename',
            'lynxflow/operators/stats',
            'lynxflow/operators/eventstats',
            'lynxflow/operators/streamstats',
            'lynxflow/operators/sort',
            'lynxflow/operators/head',
            'lynxflow/operators/tail',
            'lynxflow/operators/dedup',
            'lynxflow/operators/sample',
            'lynxflow/operators/join',
            'lynxflow/operators/union',
            'lynxflow/operators/explode',
            'lynxflow/operators/describe',
            'lynxflow/operators/top',
            'lynxflow/operators/rare',
            'lynxflow/operators/every',
            'lynxflow/operators/rate',
            'lynxflow/operators/latency',
            'lynxflow/operators/percentiles',
            'lynxflow/operators/proportion',
            'lynxflow/operators/facets',
            'lynxflow/operators/impact',
            'lynxflow/operators/baseline',
            'lynxflow/operators/changes',
            'lynxflow/operators/exemplars',
            'lynxflow/operators/patterns',
            'lynxflow/operators/compare',
            'lynxflow/operators/outliers',
            'lynxflow/operators/sessionize',
            'lynxflow/operators/transaction',
            'lynxflow/operators/trace',
            'lynxflow/operators/topology',
            'lynxflow/operators/correlate',
            'lynxflow/operators/rollup',
            'lynxflow/operators/xyseries',
            'lynxflow/operators/materialize',
            'lynxflow/operators/tee',
            'lynxflow/operators/use',
          ],
        },
        'lynxflow/functions',
        'lynxflow/aggregates',
      ],
    },
    // RFC-002 P10: Lynx Flow Reference (Legacy SPL2) sidebar category removed.
    // The generated LynxFlow reference (lynxflow/) is the canonical documentation.
    {
      type: 'category',
      label: 'Sigma',
      link: {type: 'doc', id: 'sigma/index'},
      items: [
        'sigma/compat',
        'sigma/spl2-mapping',
        'sigma/pipelines',
        'sigma/cookbook',
        'sigma/troubleshooting',
        'sigma/limitations',
        'sigma/drift-runbook',
        {
          type: 'category',
          label: 'Tutorials',
          items: [
            'sigma/tutorials/quickstart',
            'sigma/tutorials/bulk-conversion',
            'sigma/tutorials/windows-evtx',
            'sigma/tutorials/cloudtrail',
            'sigma/tutorials/pipelines',
            'sigma/tutorials/scheduled-detection',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'CLI Reference',
      items: [
        'cli/overview',
        'cli/query',
        'cli/ingest',
        'cli/tail',
        'cli/server',
        'cli/shortcuts',
        'cli/mv',
        'cli/auth',
        'cli/config-cmd',
        'cli/shell',
        'cli/bench-demo',
        'cli/output-formats',
        'cli/completion',
        'cli/install',
        'cli/shippers',
      ],
    },
    {
      type: 'category',
      label: 'REST API',
      items: [
        'api/overview',
        'api/ingest',
        'api/query',
        'api/tail-histogram',
        'api/fields',
        'api/saved-queries',
        'api/views',
        'api/server',
        'api/compatibility',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'configuration/overview',
        'configuration/server',
        'configuration/storage',
        'configuration/query',
        'configuration/ingest',
        'configuration/syslog',
        'configuration/s3-tiering',
        'configuration/cluster',
        'configuration/environment-variables',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/single-node',
        'deployment/docker',
        'deployment/kubernetes',
        'deployment/small-cluster',
        'deployment/large-cluster',
        'deployment/s3-setup',
        'deployment/tls-auth',
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      items: [
        'migration/from-splunk',
        'migration/from-elasticsearch',
        'migration/from-loki',
        'migration/from-grep',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/monitoring',
        'operations/backup-restore',
        'operations/retention',
        'operations/rebalancing',
        'operations/performance-tuning',
        'operations/shipper-conformance',
        'operations/troubleshooting',
        'operations/upgrading',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/storage-engine',
        'architecture/segment-format',
        'architecture/query-engine',
        'architecture/indexing',
        'architecture/es-stubs',
        'architecture/distributed',
        'architecture/design-decisions',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/development-setup',
        'contributing/project-structure',
        'contributing/coding-guidelines',
      ],
    },
  ],
};

export default sidebars;
